# Nome do projeto a ser definido para setar todos os argumentos necessarios "preferenciamente sempre o nome do diretório do projeto para que o alias que criei funcione"
name: laravel-mvc

services:
    app:
        # O build especifíca o caminho para o Dockerfile a ser utilizado, como o mesmo está na raiz é usado o `.`
        container_name: $COMPOSE_PROJECT_NAME-dev-php-fpm
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
            args:
                PHP_VERSION: "8.3.20-fpm-alpine3.20"
                PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
                # Obtém automaticamente o nome do projeto a partir da variável padrão linux
                USER_NAME: "${USER:-www-data}"
        ports:
            - 8086:80
        volumes:
            # Bind mount - que conecta o diretório atual ao contêiner da aplicação, excluindo o vendor
            - ./:/var/www/${COMPOSE_PROJECT_NAME}
